version: '2'
services:
    myapp:
        container_name: "myapp"
        image: isa-server
        ports:
            - 8080:9000
        links:
            - mongodb
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        command: mongod 
        ports:
            - 27000:27017